// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Ping } from '../../omf/message/ping.js';
import { Pong } from '../../omf/message/pong.js';


export enum OMFMessagePayload {
  NONE = 0,
  Ping = 1,
  Pong = 2
}

export function unionToOmfmessagePayload(
  type: OMFMessagePayload,
  accessor: (obj:Ping|Pong) => Ping|Pong|null
): Ping|Pong|null {
  switch(OMFMessagePayload[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(new Ping())! as Ping;
    case 'Pong': return accessor(new Pong())! as Pong;
    default: return null;
  }
}

export function unionListToOmfmessagePayload(
  type: OMFMessagePayload, 
  accessor: (index: number, obj:Ping|Pong) => Ping|Pong|null, 
  index: number
): Ping|Pong|null {
  switch(OMFMessagePayload[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(index, new Ping())! as Ping;
    case 'Pong': return accessor(index, new Pong())! as Pong;
    default: return null;
  }
}
