// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Pong {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Pong {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPong(bb:flatbuffers.ByteBuffer, obj?:Pong):Pong {
  return (obj || new Pong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPong(bb:flatbuffers.ByteBuffer, obj?:Pong):Pong {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Pong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startPong(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endPong(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPong(builder:flatbuffers.Builder):flatbuffers.Offset {
  Pong.startPong(builder);
  return Pong.endPong(builder);
}
}
